---
title: "Good Exercising"
author: "Marcio Mutti"
date: "January, 31, 2016"
output: html_document
---

This paper aims to model the data available at [link](http://groupware.les.inf.puc-rio.br/har) to predict how well the workout was done based on the measured data.

```{r}
library(caret, quietly = TRUE)
library(dplyr)
setwd("~/R/licoes/")
set.seed(654321)
if (!file.exists("pml-training.csv")) {
  download.file("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv",
                destfile = "pml-training.csv", method = "curl")
}
if (!file.exists("pml-testing.csv")) {
  download.file("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv",
                destfile = "pml-testing.csv", method = "curl")
}
pml_training <- read.csv("pml-training.csv", na.strings=c("NA","#DIV/0!",""))
#pml_training <- pml_training[-1]
pml_testing <- read.csv("pml-testing.csv", na.strings=c("NA","#DIV/0!",""))
#pml_testing <- pml_testing[-1]
#test_fit1 <- train(classe ~ ., data=pml_training, method = "rpart")
#test_fit2 <- train(classe ~ ., data=pml_training, method = "rf")
```
There are some variables in the data that might not add real information to the analysis, and a lot of them are whitespaces. After that, lets use the Random Forest method to create a model
```{r}
variables <- c("new_window", "roll_belt", "pitch_belt", "yaw_belt",
               "total_accel_belt", "kurtosis_roll_belt", "kurtosis_picth_belt", "skewness_roll_belt",
               "skewness_roll_belt.1", "max_roll_belt", "max_picth_belt", "max_yaw_belt",
               "min_roll_belt", "min_pitch_belt", "min_yaw_belt", "amplitude_roll_belt",
               "amplitude_pitch_belt", "var_total_accel_belt", "avg_roll_belt", "stddev_roll_belt",
               "var_roll_belt", "avg_pitch_belt", "stddev_pitch_belt", "var_pitch_belt",
               "avg_yaw_belt", "stddev_yaw_belt", "var_yaw_belt", "gyros_belt_x",
               "gyros_belt_y", "gyros_belt_z", "accel_belt_x", "accel_belt_y",
               "accel_belt_z", "magnet_belt_x", "magnet_belt_y", "magnet_belt_z",
               "roll_arm", "pitch_arm", "yaw_arm", "total_accel_arm",
               "var_accel_arm", "avg_roll_arm", "stddev_roll_arm", "var_roll_arm",
               "avg_pitch_arm", "stddev_pitch_arm", "var_pitch_arm", "avg_yaw_arm",
               "stddev_yaw_arm", "var_yaw_arm", "gyros_arm_x", "gyros_arm_y",
               "gyros_arm_z", "accel_arm_x", "accel_arm_y", "accel_arm_z",
               "magnet_arm_x", "magnet_arm_y", "magnet_arm_z", "kurtosis_roll_arm",
               "kurtosis_picth_arm", "kurtosis_yaw_arm", "skewness_roll_arm", "skewness_pitch_arm",
               "skewness_yaw_arm", "max_roll_arm", "max_picth_arm", "max_yaw_arm",
               "min_roll_arm", "min_pitch_arm", "min_yaw_arm", "amplitude_roll_arm",
               "amplitude_pitch_arm", "amplitude_yaw_arm", "roll_dumbbell", "pitch_dumbbell",
               "yaw_dumbbell", "kurtosis_roll_dumbbell", "kurtosis_picth_dumbbell", "skewness_roll_dumbbell",
               "skewness_pitch_dumbbell", "max_roll_dumbbell", "max_picth_dumbbell", "max_yaw_dumbbell",
               "min_roll_dumbbell", "min_pitch_dumbbell", "min_yaw_dumbbell", "amplitude_roll_dumbbell",
               "amplitude_pitch_dumbbell", "total_accel_dumbbell", "var_accel_dumbbell", "avg_roll_dumbbell",
               "stddev_roll_dumbbell", "var_roll_dumbbell", "avg_pitch_dumbbell", "stddev_pitch_dumbbell",
               "var_pitch_dumbbell", "avg_yaw_dumbbell", "stddev_yaw_dumbbell", "var_yaw_dumbbell",
               "gyros_dumbbell_x", "gyros_dumbbell_y", "gyros_dumbbell_z", "accel_dumbbell_x",
               "accel_dumbbell_y", "accel_dumbbell_z", "magnet_dumbbell_x", "magnet_dumbbell_y",
               "magnet_dumbbell_z", "roll_forearm", "pitch_forearm", "yaw_forearm",
               "kurtosis_roll_forearm", "kurtosis_picth_forearm", "skewness_roll_forearm",
               "skewness_pitch_forearm", "max_roll_forearm", "max_picth_forearm", 
               "max_yaw_forearm", "min_roll_forearm",
               "min_pitch_forearm", "min_yaw_forearm", "amplitude_roll_forearm", "amplitude_pitch_forearm",
               "total_accel_forearm", "var_accel_forearm", "avg_roll_forearm", "stddev_roll_forearm",
               "var_roll_forearm", "avg_pitch_forearm", "stddev_pitch_forearm", "var_pitch_forearm",
               "avg_yaw_forearm", "stddev_yaw_forearm", "var_yaw_forearm", "gyros_forearm_x",
               "gyros_forearm_y", "gyros_forearm_z", "accel_forearm_x", "accel_forearm_y",
               "accel_forearm_z", "magnet_forearm_x", "magnet_forearm_y", "magnet_forearm_z", "classe")
novo_training <- pml_training[,variables]
novo_testing <- pml_testing[,variables[-length(variables)]]
Fit_Model <- randomForest(classe ~ .,
                          data=novo_training, 
                          ntree=500,
                          mtry=12,
                          importance=TRUE,
                          na.action=randomForest::na.roughfix,
                          replace=FALSE,
                          xtest = na.omit(novo_testing))
Fit_Model
```
